apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: ethics-migration
  name: ethics-migration
  namespace: omb-apps
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: ethics-migration
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: production
        image: IMAGE_SPEC
        imagePullPolicy: Always
        name: ethics-migration
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /programdata/docker/secrets/
          name: secret
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry2.omb.gov-credentials
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secret
        secret:
          defaultMode: 292
          optional: false
          secretName: ethics
